name: Check Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Commit Messages
        run: |
          COMMITS=$(git log --format=%s -n 1)
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Validate Conventional Commit
        id: validate
        run: |
          echo "$COMMITS" | grep -Eiq "^(feat|fix|chore|docs|style|refactor|perf|test|build|ci)(\(.+\))?: .{1,100}$" || exit 1

      - name: Close PR if Commit is Invalid
        if: failure()
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "PR closed due to non-conventional commit message. Please follow the Conventional Commit guidelines."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
