name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"  # Eveyday 12AM UTC
  workflow_dispatch:  # Manual Execution possibile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t hkwon7/fastapi-beyond-crud:latest .
          docker push hkwon7/fastapi-beyond-crud:latest

  run-tests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
          echo "MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          
          docker compose up -d
          sleep 10  # Wait until service starts
          docker exec -i fastapi-beyond-crud-web-1 pytest --maxfail=5 --disable-warnings

  notify-failure:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure()

    steps:
      - name: Send Email on Failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.ETHEREAL_USER }}
          password: ${{ secrets.ETHEREAL_PASS }}
          subject: "Nightly Build Failed!"
          body: "The nightly build for fastapi-beyond-crud failed. Check the logs for details."
          to: "hkwon7@dons.usfca.edu"
          from: "GitHub Actions <no-reply@example.com>"
